# Generated by Django 4.0.6 on 2022-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Inserido en el sistema')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
                ('iva', models.CharField(choices=[(10.5, '10.5'), (21, '21'), (27, '27')], max_length=10, verbose_name='IVA')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%d/%m/%Y', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es activo?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Inserido en el sistema')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('category', models.ManyToManyField(blank=True, to='product.category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
