# Generated by Django 4.0.6 on 2022-08-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.CharField(choices=[('10.5', '10.5'), ('21', '21'), ('27', '27')], max_length=10, verbose_name='IVA'),
        ),
    ]
