# Generated by Django 4.0.6 on 2023-01-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_payment_slip_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='charger',
        ),
        migrations.DeleteModel(
            name='DocCategory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
