# Generated by Django 4.0.6 on 2022-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='¿Pagado?'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='pay_condition',
            field=models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90')], max_length=10, verbose_name='Condición de pago'),
        ),
    ]
