# Generated by Django 4.0.6 on 2022-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_lot_charger_alter_lot_price_alter_lot_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='pay_condition',
            field=models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90')], default='30', max_length=10, null=True, verbose_name='Condición de pago'),
        ),
    ]
