# Generated by Django 4.0.6 on 2022-08-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_lot_pay_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='payment_slip',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='Factura de compra'),
        ),
    ]
