# Generated by Django 4.0.6 on 2022-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleproduct_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pay_type',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Otro', 'Otro')], default='Efectivo', max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
